export const images = [
    {
        "url":"unsplash/alarmclock.jpg",
        "name":"alarmclock.jpg"
    },
    {
        "url":"unsplash/bear.jpg",
        "name":"bear.jpg"
    },
    {
        "url":"unsplash/bridge.jpg",
        "name":"bridge.jpg"
    },
    {
        "url":"unsplash/citystreet.jpg",
        "name":"citystreet.jpg"
    },
    {
        "url":"unsplash/coffee.JPG",
        "name":"coffee.JPG"
    },
    {
        "url":"unsplash/coyote.jpg",
        "name":"coyote.jpg"
    },
    {
        "url":"unsplash/goldengate.jpg",
        "name":"goldengate.jpg"
    },
    {
        "url":"unsplash/macaque.jpg",
        "name":"macaque.jpg"
    },
    {
        "url":"unsplash/motorbike.jpg",
        "name":"motorbike.jpg"
    },
    {
        "url":"unsplash/mountains.jpg",
        "name":"mountains.jpg"
    },
    {
        "url":"unsplash/paperlamp.jpg",
        "name":"paperlamp.jpg"
    },
    {
        "url":"unsplash/pineneedles.jpg",
        "name":"pineneedles.jpg"
    },
    {
        "url":"unsplash/raspberries.jpg",
        "name":"raspberries.jpg"
    },
    {
        "url":"unsplash/transport.jpg",
        "name":"transport.jpg"
    },
    {
        "url":"unsplash/turntable.jpg",
        "name":"turntable.jpg"
    },
    {
        "url":"unsplash/typewriter.jpg",
        "name":"typewriter.jpg"
    },
    {
        "url":"unsplash/umbrella.jpg",
        "name":"umbrella.jpg"
    },
    {
        "url":"unsplash/vintagecameras.jpg",
        "name":"vintagecameras.jpg"
    },
    {
        "url":"unsplash/windows.jpg",
        "name":"windows.jpg"
    },
    {
        "url":"unsplash/womansitting.jpg",
        "name":"womansitting.jpg"
    },
    {
        "url":"blog/woman-hat.jpg",
        "name":"woman-hat.jpg"
    },
    {
        "url":"examples/balloons.jpg",
        "name":"balloons.jpg"
    },
    {
        "url":"examples/blueberries.jpg",
        "name":"blueberries.jpg"
    },
    {
        "url":"examples/bluehat.jpg",
        "name":"bluehat.jpg"
    },
    {
        "url":"examples/butterfly.jpg",
        "name":"butterfly.jpg"
    },
    {
        "url":"examples/espresso.jpg",
        "name":"espresso.jpg"
    },
    {
        "url":"examples/jellyfish.jpg",
        "name":"jellyfish.jpg"
    },
    {
        "url":"examples/kingfisher.jpg",
        "name":"kingfisher.jpg"
    },
    {
        "url":"examples/lorie.png",
        "name":"lorie.png"
    },
    {
        "url":"examples/mountain.jpg",
        "name":"mountain.jpg"
    },
    {
        "url":"examples/newt.jpg",
        "name":"newt.jpg"
    },
    {
        "url":"examples/octopus.jpg",
        "name":"octopus.jpg"
    },
    {
        "url":"examples/puffins.jpg",
        "name":"puffins.jpg"
    },
    {
        "url":"examples/redleaf.jpg",
        "name":"redleaf.jpg"
    },
    {
        "url":"examples/snake.jpg",
        "name":"snake.jpg"
    },
    {
        "url":"examples/treefrog.jpg",
        "name":"treefrog.jpg"
    },
    {
        "url":"examples/vista.png",
        "name":"vista.png"
    },
    {
        "url":"examples/womanlandscape.jpg",
        "name":"womanlandscape.jpg"
    },
    {
        "url":"gif-examples/imgix-logo-ani.gif",
        "name":"imgix-logo-ani.gif"
    }
]
